#![recursion_limit = "512"]

// Originally from https://gist.github.com/AngelicosPhosphoros/4f8c9f08656e0812f4ed3560e53bd600

// There are 3 steps to update:
// 1. get list of features using `rustc --print target-features`
// 2. put it below (it has values actual for 2020-12-06 for x86-64 target).
// 3. update https://gist.github.com/AngelicosPhosphoros/4f8c9f08656e0812f4ed3560e53bd600

macro_rules! target_features_vec {
    ($out:ident,) => {};
    ($out:ident, $feature:literal $(, $feats:literal)*)=>{
        if cfg!(target_feature = $feature){
            $out.push($feature.to_string());
        }
        target_features_vec!($out, $($feats),*)
    }
}

/// Return all cpu features which are active in this build
pub fn target_features() -> Vec<String> {
    let mut result = Vec::new();
    target_features_vec!(
        result,
        "16bit-mode",
        "32bit-mode",
        "3dnow",
        "3dnowa",
        "64bit",
        "64bit-mode",
        "adx",
        "aes",
        "amx-bf16",
        "amx-int8",
        "amx-tile",
        "avx",
        "avx2",
        "avx512bf16",
        "avx512bitalg",
        "avx512bw",
        "avx512cd",
        "avx512dq",
        "avx512er",
        "avx512f",
        "avx512ifma",
        "avx512pf",
        "avx512vbmi",
        "avx512vbmi2",
        "avx512vl",
        "avx512vnni",
        "avx512vp2intersect",
        "avx512vpopcntdq",
        "bmi",
        "bmi2",
        "branchfusion",
        "cldemote",
        "clflushopt",
        "clwb",
        "clzero",
        "cmov",
        "cx16",
        "cx8",
        "enqcmd",
        "ermsb",
        "f16c",
        "false-deps-lzcnt-tzcnt",
        "false-deps-popcnt",
        "fast-11bytenop",
        "fast-15bytenop",
        "fast-7bytenop",
        "fast-bextr",
        "fast-gather",
        "fast-hops",
        "fast-lzcnt",
        "fast-scalar-fsqrt",
        "fast-scalar-shift-masks",
        "fast-shld-rotate",
        "fast-variable-shuffle",
        "fast-vector-fsqrt",
        "fast-vector-shift-masks",
        "fma",
        "fma4",
        "fsgsbase",
        "fxsr",
        "gfni",
        "idivl-to-divb",
        "idivq-to-divl",
        "invpcid",
        "lea-sp",
        "lea-uses-ag",
        "lvi-cfi",
        "lvi-load-hardening",
        "lwp",
        "lzcnt",
        "macrofusion",
        "merge-to-threeway-branch",
        "mmx",
        "movbe",
        "movdir64b",
        "movdiri",
        "mpx",
        "mwaitx",
        "nopl",
        "pad-short-functions",
        "pclmul",
        "pconfig",
        "pku",
        "popcnt",
        "prefer-128-bit",
        "prefer-256-bit",
        "prefer-mask-registers",
        "prefetchwt1",
        "prfchw",
        "ptwrite",
        "rdpid",
        "rdrnd",
        "rdseed",
        "retpoline",
        "retpoline-external-thunk",
        "retpoline-indirect-branches",
        "retpoline-indirect-calls",
        "rtm",
        "sahf",
        "serialize",
        "seses",
        "sgx",
        "sha",
        "shstk",
        "slow-3ops-lea",
        "slow-incdec",
        "slow-lea",
        "slow-pmaddwd",
        "slow-pmulld",
        "slow-shld",
        "slow-two-mem-ops",
        "slow-unaligned-mem-16",
        "slow-unaligned-mem-32",
        "soft-float",
        "sse",
        "sse-unaligned-mem",
        "sse2",
        "sse3",
        "sse4.1",
        "sse4.2",
        "sse4a",
        "ssse3",
        "tbm",
        "tsxldtrk",
        "use-aa",
        "use-glm-div-sqrt-costs",
        "vaes",
        "vpclmulqdq",
        "vzeroupper",
        "waitpkg",
        "wbnoinvd",
        "x87",
        "xop",
        "xsave",
        "xsavec",
        "xsaveopt",
        "xsaves"
    );
    result
}
